In [1]:
import pandas as pd
import sqlite3

In [2]:
#Load file
apps = pd.read_excel(r"C:\Users\admin\Downloads\Google Play Store Analysis\Googleplaystore_cleaned.xlsx")

In [3]:
apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,1.0,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,1.0,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510.0,8.0,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,2.0,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.0,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up

In [4]:
#Createing the Database Connection
conn = sqlite3.connect("google_playstore.db")

In [7]:
#Store the DataFrame as a SQL Table
apps.to_sql(
    name="apps",
    con=conn,
    if_exists="replace",
    index=False
)

10841

In [8]:
#Checking if the Table Exists
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

   name
0  apps

In [9]:
#Read Data Using SQL
query = """
SELECT *
FROM apps
LIMIT 5;
"""

pd.read_sql(query, conn)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,1.0,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07 00:00:00,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,1.0,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15 00:00:00,2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510.0,8.0,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01 00:00:00,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,2.0,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08 00:00:00,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.0,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20 00:00:00,1.1,4.4 and up

In [10]:
#Count the Number of Apps
query = """
SELECT COUNT(*) AS Total_Apps
FROM apps;
"""
pd.read_sql(query,conn)

   Total_Apps
0       10841

In [12]:
#Display First 10 Records
query = """
SELECT *
FROM Apps
LIMIT 10;
"""
pd.read_sql(query,conn)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,1.0,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07 00:00:00,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,1.0,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15 00:00:00,2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510.0,8.0,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01 00:00:00,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,2.0,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08 00:00:00,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.0,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20 00:00:00,1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167.0,5.0,50000.0,Free,0.0,Everyone,Art & Design,2017-03-26 00:00:00,1,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178.0,1.0,50000.0,Free,0.0,Everyone,Art & Design,2018-04-26 00:00:00,1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815.0,2.0,1000000.0,Free,0.0,Everyone,Art & Design,2018-06-14 00:00:00,6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791.0,3.0,1000000.0,Free,0.0,Everyone,Art & Design,2017-09-20 00:00:00,2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121.0,3.0,10000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-07-03 00:00:00,2.8,4.0.3 and up

In [16]:
#Display Selected Columns
query ="""
SELECT App,
       Category,
       Rating,
       Installs
FROM apps
LIMIT 10;
"""
pd.read_sql(query,conn)

,App,Category,Rating,Installs
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,10000.0
1,Coloring book moana,ART_AND_DESIGN,3.9,500000.0
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,5000000.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,50000000.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,100000.0
5,Paper flowers instructions,ART_AND_DESIGN,4.4,50000.0
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,50000.0
7,Infinite Painter,ART_AND_DESIGN,4.1,1000000.0
8,Garden Coloring Book,ART_AND_DESIGN,4.4,1000000.0
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,10000.0

In [17]:
#List All Categories
query ="""
SELECT DISTINCT Category
FROM apps
ORDER BY Category;
"""

pd.read_sql(query,conn)

               Category
0                   1.9
1        ART_AND_DESIGN
2     AUTO_AND_VEHICLES
3                BEAUTY
4   BOOKS_AND_REFERENCE
5              BUSINESS
6                COMICS
7         COMMUNICATION
8                DATING
9             EDUCATION
10        ENTERTAINMENT
11               EVENTS
12               FAMILY
13              FINANCE
14       FOOD_AND_DRINK
15                 GAME
16   HEALTH_AND_FITNESS
17       HOUSE_AND_HOME
18   LIBRARIES_AND_DEMO
19            LIFESTYLE
20  MAPS_AND_NAVIGATION
21              MEDICAL
22   NEWS_AND_MAGAZINES
23            PARENTING
24      PERSONALIZATION
25          PHOTOGRAPHY
26         PRODUCTIVITY
27             SHOPPING
28               SOCIAL
29               SPORTS
30                TOOLS
31     TRAVEL_AND_LOCAL
32        VIDEO_PLAYERS
33              WEATHER

In [26]:
#Removing 1.9 
cursor = conn.cursor()
cursor.execute("""
DELETE FROM apps
WHERE Category = '1.9'
""")

conn.commit()

In [27]:
cursor.execute("""
SELECT *
FROM apps
WHERE Category = '1.9'
""")

print(cursor.fetchall())

[]

In [28]:
#Count Categories
query = """
SELECT COUNT(DISTINCT Category) AS Total_Categories
FROM apps;
"""
pd.read_sql(query, conn)

   Total_Categories
0                33

In [29]:
#Show Free Apps
query = """
SELECT App,
       Category
FROM apps
WHERE Type = "Free";
"""

pd.read_sql(query,conn)

                                                     App             Category
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite â€“ FREE Live Cool Themes, Hid...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10034                                   Sya9a Maroc - FR               FAMILY
10035                   Fr. Mike Schmitz Audio Teachings               FAMILY
10036                             Parkinson Exercices FR              MEDICAL
10037                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10038      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

[10039 rows x 2 columns]

In [30]:
#Apps with Rating Greater Than 4.5
query = """
SELECT App,
       Rating
FROM apps
WHERE Rating > 4.5;
"""

pd.read_sql(query,conn)

                                                    App  Rating
0     U Launcher Lite â€“ FREE Live Cool Themes, Hid...     4.7
1                         Kids Paint Free - Drawing Fun     4.7
2                                 Mandala Coloring Book     4.6
3          Photo Designer - Write your name with shapes     4.7
4                                          ibis Paint X     4.6
...                                                 ...     ...
1912                                  Fr Lupupa Sermons     4.8
1913                                    Fr. Daoud Lamei     5.0
1914                     Bulgarian French Dictionary Fr     4.6
1915                                        Chemin (fr)     4.8
1916                   Fr. Mike Schmitz Audio Teachings     5.0

[1917 rows x 2 columns]

In [32]:
#Paid Apps with Rating Above 4.5
query = """
SELECT App,
       Rating,
       Price
FROM apps
WHERE Type = "Paid" AND Rating > 4.5;
"""

pd.read_sql(query,conn)

                                               App  Rating  Price
0    TurboScan: scan documents and receipts in PDF     4.7   4.99
1                   Tiny Scanner Pro: PDF Doc Scan     4.8   4.99
2    TurboScan: scan documents and receipts in PDF     4.7   4.99
3                   Tiny Scanner Pro: PDF Doc Scan     4.8   4.99
4                              Sago Mini Hat Maker     4.9   3.99
..                                             ...     ...    ...
203           Kernel Manager for Franco Kernel âœ¨     4.8   3.49
204                      FL SW Fishing Regulations     4.6   1.99
205                                     Solitaire+     4.6   2.99
206                                       FO Bixby     5.0   0.99
207                                        Mu.F.O.     5.0   0.99

[208 rows x 3 columns]

In [33]:
#Highly Rated OR Highly Installed Apps
query = """
SELECT App,
       Rating,
       Installs
FROM apps
WHERE Rating>4.8
OR Installs>10000000;
"""
pd.read_sql(query, conn)

                                                    App  Rating    Installs
0                                 Sketch - Draw & Paint     4.5  50000000.0
1     Tickets SDA 2018 and Exam from the State Traff...     4.9    100000.0
2                        CDL Practice Test 2018 Edition     4.9    100000.0
3                 DMV Permit Practice Test 2018 Edition     4.9    100000.0
4                               Tickets + PDA 2018 Exam     4.9   1000000.0
...                                                 ...     ...         ...
1184                              GKPB FP Online Church     5.0      1000.0
1185                                   Monster Ride Pro     5.0        10.0
1186                                Fr Ignacio Outreach     4.9      1000.0
1187                                    Fr. Daoud Lamei     5.0      1000.0
1188                   Fr. Mike Schmitz Audio Teachings     5.0       100.0

[1189 rows x 3 columns]

In [34]:
#Apps Rated Between 4.0 and 4.5
query = """
SELECT App,
       Rating,
       Price
FROM apps
WHERE Rating BETWEEN 4.0 AND 4.5;
"""

pd.read_sql(query,conn)

                                                 App  Rating  Price
0     Photo Editor & Candy Camera & Grid & ScrapBook     4.1    0.0
1                              Sketch - Draw & Paint     4.5    0.0
2              Pixel Draw - Number Art Coloring Book     4.3    0.0
3                         Paper flowers instructions     4.4    0.0
4                                   Infinite Painter     4.1    0.0
...                                              ...     ...    ...
6920                                        FR Forms     4.3    0.0
6921                                Sya9a Maroc - FR     4.5    0.0
6922                          Parkinson Exercices FR     4.3    0.0
6923                   The SCP Foundation DB fr nn5n     4.5    0.0
6924   iHoroscope - 2018 Daily Horoscope & Astrology     4.5    0.0

[6925 rows x 3 columns]

In [35]:
#Average Rating
query = """
SELECT ROUND(AVG(Rating),2) AS Average_Rating
FROM apps;
"""
pd.read_sql(query, conn)

   Average_Rating
0            4.21

In [36]:
#Highest Installs
query = """
SELECT MAX(Installs) AS Maximum_Installs
FROM apps;
"""
pd.read_sql(query, conn)

   Maximum_Installs
0      1.000000e+09

In [37]:
#Lowest Rating
query = """
SELECT MIN(Rating) AS Minimum_Rating
FROM apps;
"""
pd.read_sql(query, conn)

   Minimum_Rating
0             1.0

In [38]:
#Total Reviews
query = """
SELECT SUM(Reviews) AS Total_Reviews
FROM apps;
"""
pd.read_sql(query, conn)

   Total_Reviews
0   4.814617e+09

In [39]:
#Average Price of Paid Apps
query = """
SELECT ROUND(AVG(Price),2) AS Average_Price
FROM apps
WHERE Type='Paid';
"""
pd.read_sql(query, conn)

   Average_Price
0          13.92

In [40]:
query = """
SELECT Category,
ROUND(AVG(Rating),2) AS Average_Rating
FROM apps
GROUP BY Category
ORDER BY Average_Rating DESC;
"""
pd.read_sql(query, conn)

               Category  Average_Rating
0                EVENTS            4.40
1             EDUCATION            4.39
2        ART_AND_DESIGN            4.36
3   BOOKS_AND_REFERENCE            4.34
4       PERSONALIZATION            4.33
5             PARENTING            4.30
6                  GAME            4.29
7    HEALTH_AND_FITNESS            4.28
8                BEAUTY            4.28
9                SOCIAL            4.26
10             SHOPPING            4.26
11              WEATHER            4.25
12               SPORTS            4.24
13         PRODUCTIVITY            4.23
14              MEDICAL            4.22
15   LIBRARIES_AND_DEMO            4.21
16       HOUSE_AND_HOME            4.21
17    AUTO_AND_VEHICLES            4.21
18          PHOTOGRAPHY            4.20
19               FAMILY            4.20
20       FOOD_AND_DRINK            4.19
21        COMMUNICATION            4.18
22             BUSINESS            4.18
23   NEWS_AND_MAGAZINES            4.16
24               COMICS            4.16
25              FINANCE            4.15
26     TRAVEL_AND_LOCAL            4.13
27            LIFESTYLE            4.13
28        ENTERTAINMENT            4.13
29        VIDEO_PLAYERS            4.08
30                TOOLS            4.08
31  MAPS_AND_NAVIGATION            4.08
32               DATING            4.03

Categories such as Events, Education, and Art & Design have some of the highest average app ratings.Businesses can analyze highly rated categories to understand user preferences and identify features that contribute to positive user experiences. Developers can use these insights to improve app quality and customer satisfaction.

In [41]:
#Total Number of Apps by Category
query = """
SELECT Category,
COUNT(*) AS Total_Apps
FROM apps
GROUP BY Category
ORDER BY Total_Apps DESC;
"""
pd.read_sql(query, conn)

               Category  Total_Apps
0                FAMILY        1972
1                  GAME        1144
2                 TOOLS         843
3               MEDICAL         463
4              BUSINESS         460
5          PRODUCTIVITY         424
6       PERSONALIZATION         392
7         COMMUNICATION         387
8                SPORTS         384
9             LIFESTYLE         382
10              FINANCE         366
11   HEALTH_AND_FITNESS         341
12          PHOTOGRAPHY         335
13               SOCIAL         295
14   NEWS_AND_MAGAZINES         283
15             SHOPPING         260
16     TRAVEL_AND_LOCAL         258
17               DATING         234
18  BOOKS_AND_REFERENCE         231
19        VIDEO_PLAYERS         175
20            EDUCATION         156
21        ENTERTAINMENT         149
22  MAPS_AND_NAVIGATION         137
23       FOOD_AND_DRINK         127
24       HOUSE_AND_HOME          88
25   LIBRARIES_AND_DEMO          85
26    AUTO_AND_VEHICLES          85
27              WEATHER          82
28       ART_AND_DESIGN          65
29               EVENTS          64
30            PARENTING          60
31               COMICS          60
32               BEAUTY          53

FAMILY has the highest number of apps.
Categories with a large number of apps are highly competitive, making it harder for new apps to gain visibility.
Categories with fewer apps may present market opportunities if there is sufficient user demand.
Google can use this information to understand category distribution and support strategic decisions around app discovery.

In [42]:
#Average Number of Reviews by Category
query = """
SELECT Category,
ROUND(AVG(Reviews),0) AS Average_Reviews
FROM apps
GROUP BY Category
ORDER BY Average_Reviews DESC;
"""
pd.read_sql(query, conn)

               Category  Average_Reviews
0         COMMUNICATION        2107138.0
1                SOCIAL        2105903.0
2                  GAME        1385859.0
3           PHOTOGRAPHY         637363.0
4         VIDEO_PLAYERS         630744.0
5              SHOPPING         442466.0
6         ENTERTAINMENT         397169.0
7                 TOOLS         324063.0
8          PRODUCTIVITY         269144.0
9             EDUCATION         253819.0
10     TRAVEL_AND_LOCAL         242705.0
11      PERSONALIZATION         227924.0
12  MAPS_AND_NAVIGATION         223790.0
13               FAMILY         208026.0
14   NEWS_AND_MAGAZINES         192229.0
15               SPORTS         184454.0
16              WEATHER         178107.0
17   HEALTH_AND_FITNESS         111125.0
18  BOOKS_AND_REFERENCE          95061.0
19       FOOD_AND_DRINK          69947.0
20               COMICS          56388.0
21              FINANCE          47953.0
22       HOUSE_AND_HOME          45186.0
23            LIFESTYLE          33725.0
24               DATING          31159.0
25             BUSINESS          30336.0
26       ART_AND_DESIGN          26376.0
27            PARENTING          15972.0
28    AUTO_AND_VEHICLES          13690.0
29   LIBRARIES_AND_DEMO          12201.0
30               BEAUTY           7476.0
31              MEDICAL           3425.0
32               EVENTS           2516.0

Categories such as COMMUNICATION, SOCIAL, and GAME tend to have much higher average review counts.A high average number of reviews suggests strong user engagement and a large active user base.
Developers entering categories with high engagement may reach a wider audience but will also face more competition.
Google can use review activity as one indicator when evaluating app popularity and user interaction.

In [43]:
#Total Installs By Category
query = """
SELECT Category,
SUM(Installs) AS Total_Installs
FROM apps
GROUP BY Category
ORDER BY Total_Installs DESC;
"""
pd.read_sql(query, conn)

               Category  Total_Installs
0                  GAME    3.508602e+10
1         COMMUNICATION    3.264728e+10
2          PRODUCTIVITY    1.417609e+10
3                SOCIAL    1.406987e+10
4                 TOOLS    1.145277e+10
5                FAMILY    1.025826e+10
6           PHOTOGRAPHY    1.008825e+10
7    NEWS_AND_MAGAZINES    7.496318e+09
8      TRAVEL_AND_LOCAL    6.868887e+09
9         VIDEO_PLAYERS    6.222003e+09
10             SHOPPING    3.247849e+09
11        ENTERTAINMENT    2.869160e+09
12      PERSONALIZATION    2.325495e+09
13  BOOKS_AND_REFERENCE    1.921470e+09
14               SPORTS    1.751174e+09
15   HEALTH_AND_FITNESS    1.583073e+09
16             BUSINESS    1.001915e+09
17              FINANCE    8.766487e+08
18            EDUCATION    8.714520e+08
19  MAPS_AND_NAVIGATION    7.242819e+08
20            LIFESTYLE    5.376435e+08
21              WEATHER    4.261005e+08
22       FOOD_AND_DRINK    2.738988e+08
23               DATING    2.643108e+08
24       HOUSE_AND_HOME    1.687125e+08
25       ART_AND_DESIGN    1.243381e+08
26   LIBRARIES_AND_DEMO    6.299591e+07
27               COMICS    5.608615e+07
28              MEDICAL    5.325744e+07
29    AUTO_AND_VEHICLES    5.313021e+07
30            PARENTING    3.152111e+07
31               BEAUTY    2.719705e+07
32               EVENTS    1.597316e+07

Game and Communication category has highest total installs.Categories with the highest total installs represent strong user demand and market potential. Businesses and developers can focus on these categories to maximize app reach, user acquisition, and revenue opportunities.

In [44]:
#No of Paid Apps in each  Category
query = """
SELECT Category,
COUNT(*) AS Paid_Apps
FROM apps
WHERE Type='Paid'
GROUP BY Category
ORDER BY Paid_Apps DESC;
"""
pd.read_sql(query, conn)

               Category  Paid_Apps
0                FAMILY        191
1               MEDICAL        109
2       PERSONALIZATION         83
3                  GAME         83
4                 TOOLS         78
5          PRODUCTIVITY         28
6   BOOKS_AND_REFERENCE         28
7         COMMUNICATION         27
8                SPORTS         24
9           PHOTOGRAPHY         22
10            LIFESTYLE         19
11              FINANCE         17
12   HEALTH_AND_FITNESS         16
13             BUSINESS         14
14     TRAVEL_AND_LOCAL         12
15              WEATHER          8
16               DATING          7
17  MAPS_AND_NAVIGATION          5
18        VIDEO_PLAYERS          4
19            EDUCATION          4
20               SOCIAL          3
21    AUTO_AND_VEHICLES          3
22       ART_AND_DESIGN          3
23             SHOPPING          2
24            PARENTING          2
25   NEWS_AND_MAGAZINES          2
26       FOOD_AND_DRINK          2
27        ENTERTAINMENT          2
28   LIBRARIES_AND_DEMO          1
29               EVENTS          1

Categories such as FAMILY, MEDICAL, and PERSONALIZATION appear to have stronger opportunities for paid apps, suggesting users in these categories are more willing to purchase premium features or specialized applications.
Categories dominated by free apps may rely more on advertising or in-app purchases as revenue models.

In [6]:
#Categories with More Than 300 Apps
query = """
SELECT Category,
COUNT(*) AS Total_apps
FROM apps
GROUP BY Category
HAVING COUNT(*)>300;
"""

pd.read_sql(query,conn)

              Category  Total_apps
0             BUSINESS         460
1        COMMUNICATION         387
2               FAMILY        1972
3              FINANCE         366
4                 GAME        1144
5   HEALTH_AND_FITNESS         341
6            LIFESTYLE         382
7              MEDICAL         463
8      PERSONALIZATION         392
9          PHOTOGRAPHY         335
10        PRODUCTIVITY         424
11              SPORTS         384
12               TOOLS         843

A total of 13 categories have more than 300 apps.
FAMILY, GAME, and TOOLS are highly competitive markets because they contain the largest number of apps.
Businesses planning to launch apps in these categories need strong differentiation through better features, user experience, ratings, or marketing.

In [10]:
#Categories with Average Rating Above 4.5
query = """
SELECT Category,
AVG(Rating) AS Avg_Rating
FROM apps
GROUP BY Category
HAVING AVG(Rating)> 4.5;
"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [Category, Avg_Rating]
Index: []

In [12]:
#Categories with More Than 1 Billion Total Installs
query = """
SELECT Category,
SUM(Installs) AS Total_Installs
FROM apps
GROUP BY Category
HAVING SUM(Installs)>1000000000
ORDER BY Total_Installs DESC;
"""
pd.read_sql(query, conn)

               Category  Total_Installs
0                  GAME    3.508602e+10
1         COMMUNICATION    3.264728e+10
2          PRODUCTIVITY    1.417609e+10
3                SOCIAL    1.406987e+10
4                 TOOLS    1.145277e+10
5                FAMILY    1.025826e+10
6           PHOTOGRAPHY    1.008825e+10
7    NEWS_AND_MAGAZINES    7.496318e+09
8      TRAVEL_AND_LOCAL    6.868887e+09
9         VIDEO_PLAYERS    6.222003e+09
10             SHOPPING    3.247849e+09
11        ENTERTAINMENT    2.869160e+09
12      PERSONALIZATION    2.325495e+09
13  BOOKS_AND_REFERENCE    1.921470e+09
14               SPORTS    1.751174e+09
15   HEALTH_AND_FITNESS    1.583073e+09
16             BUSINESS    1.001915e+09

Categories such as GAME, COMMUNICATION, TOOLS, PRODUCTIVITY, SOCIAL, and PHOTOGRAPHY  have the highest cumulative installs.Categories with over 1 billion installs have a very large user base and high market demand.

In [13]:
#App Rating Classification Using CASE Statement
query = """
SELECT App,
Rating,
CASE
WHEN Rating>=4.5 THEN 'Excellent'
WHEN Rating>=4 THEN 'Good'
ELSE 'Needs Improvement'
END AS Rating_Level
FROM apps;
"""
pd.read_sql(query, conn)

,App,Rating,Rating_Level
0,Photo Editor & Candy Camera & Grid & ScrapBook,4.1,Good
1,Coloring book moana,3.9,Needs Improvement
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",4.7,Excellent
3,Sketch - Draw & Paint,4.5,Excellent
4,Pixel Draw - Number Art Coloring Book,4.3,Good
...,...,...,...
10835,Sya9a Maroc - FR,4.5,Excellent
10836,Fr. Mike Schmitz Audio Teachings,5.0,Excellent
10837,Parkinson Exercices FR,4.3,Good
10838,The SCP Foundation DB fr nn5n,4.5,Excellent
10839,iHoroscope - 2018 Daily Horoscope & Astrology,4.5,Excellent

Excellent apps represent high customer satisfaction and are more likely to receive positive reviews and higher downloads.
Good apps perform well but may benefit from feature enhancements or bug fixes to achieve excellent ratings.
Needs Improvement apps may require immediate attention to improve user experience, fix issues, and increase customer satisfaction.

In [14]:
#App Type Classification (Free vs Paid) Using CASE Statement
query = """
SELECT App,
Price,
CASE
WHEN Price=0 THEN 'Free'
ELSE 'Paid'
END AS App_Type
FROM apps;
"""
pd.read_sql(query, conn)

                                                     App  Price App_Type
0         Photo Editor & Candy Camera & Grid & ScrapBook    0.0     Free
1                                    Coloring book moana    0.0     Free
2      U Launcher Lite â€“ FREE Live Cool Themes, Hid...    0.0     Free
3                                  Sketch - Draw & Paint    0.0     Free
4                  Pixel Draw - Number Art Coloring Book    0.0     Free
...                                                  ...    ...      ...
10835                                   Sya9a Maroc - FR    0.0     Free
10836                   Fr. Mike Schmitz Audio Teachings    0.0     Free
10837                             Parkinson Exercices FR    0.0     Free
10838                      The SCP Foundation DB fr nn5n    0.0     Free
10839      iHoroscope - 2018 Daily Horoscope & Astrology    0.0     Free

[10840 rows x 3 columns]

Free apps generally attract more users because there is no cost to download, helping businesses increase their user base.
Paid apps generate direct revenue but require users to perceive enough value to purchase them.
Categorizing apps as Free or Paid helps businesses compare user behavior, downloads, ratings, and revenue strategies across different pricing models.

In [15]:
#Apps Above Average Rating
query ="""
SELECT App,
Rating
FROM apps
WHERE Rating >(
SELECT AVG(Rating)
FROM apps);
"""

pd.read_sql(query,conn)

                                                    App  Rating
0     U Launcher Lite â€“ FREE Live Cool Themes, Hid...     4.7
1                                 Sketch - Draw & Paint     4.5
2                 Pixel Draw - Number Art Coloring Book     4.3
3                            Paper flowers instructions     4.4
4                                  Garden Coloring Book     4.4
...                                                 ...     ...
6609                                   Sya9a Maroc - FR     4.5
6610                   Fr. Mike Schmitz Audio Teachings     5.0
6611                             Parkinson Exercices FR     4.3
6612                      The SCP Foundation DB fr nn5n     4.5
6613      iHoroscope - 2018 Daily Horoscope & Astrology     4.5

[6614 rows x 2 columns]

Apps with ratings above the overall average indicate higher user satisfaction and better quality.
Businesses can analyze these high-performing apps to identify successful features, design, or user experience that contribute to positive ratings.
Developers can use these insights as benchmarks to improve lower-rated apps.

In [17]:
#Apps Above Average Installs
query = """
SELECT App,
CAST(Installs AS INTEGER) as Installs
FROM apps
WHERE Installs>(
SELECT AVG(Installs)
FROM apps
);
"""
pd.read_sql(query, conn)

                                App    Installs
0             Sketch - Draw & Paint    50000000
1           Wattpad ðŸ“– Free Books   100000000
2                     Amazon Kindle   100000000
3                 Google Play Books  1000000000
4                 Indeed Job Search    50000000
..                              ...         ...
823      Talking Tom Bubble Shooter    50000000
824  Flight Simulator: Fly Plane 3D    50000000
825              Toy Truck Rally 3D    50000000
826               Motorola FM Radio   100000000
827  Photo Editor Collage Maker Pro   100000000

[828 rows x 2 columns]

Apps with above-average installs have higher market reach and user adoption.
Businesses can analyze these successful apps to understand factors such as app category, features, pricing strategy, and user experience that contribute to higher downloads.
Developers can use these insights to improve app visibility and increase downloads for their own applications.

In [18]:
#Rank Apps by Rating
query ="""
SELECT App,
Rating,
RANK()OVER(ORDER BY Rating DESC) AS Rank_No
FROM apps;
"""
pd.read_sql(query,conn)

                                                    App  Rating  Rank_No
0                          Hojiboy Tojiboyev Life Hacks     5.0        1
1                         American Girls Mobile Numbers     5.0        1
2                                          Awake Dating     5.0        1
3                                 Spine- The dating app     5.0        1
4            Girls Live Talk - Free Text and Video Chat     5.0        1
...                                                 ...     ...      ...
10835                                    DS Creator 2.0     1.0    10825
10836                                    DT future1 cam     1.0    10825
10837                    FE Mechanical Engineering Prep     1.0    10825
10838           Familial Hypercholesterolaemia Handbook     1.0    10825
10839  Lottery Ticket Checker - Florida Results & Lotto     1.0    10825

[10840 rows x 3 columns]

Ranking helps identify the top-performing apps based on user ratings.
Businesses can analyze highly ranked apps to understand what contributes to customer satisfaction and success.
Apps with lower ranks can be prioritized for improvements to increase user ratings.

In [20]:
#Rank Apps Within Each Category
query="""
SELECT App,
Category,
Rating,
ROW_NUMBER()OVER(
PARTITION BY Category
ORDER BY Rating DESC
)AS Rank_In_Category
FROM apps;
"""

pd.read_sql(query,conn)

,App,Category,Rating,Rank_In_Category
0,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1
1,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,2
2,Cardi B Wallpaper,ART_AND_DESIGN,4.8,3
3,X Launcher Pro - IOS Style Theme & Control Center,ART_AND_DESIGN,4.8,4
4,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,5
...,...,...,...,...
10835,DS Thermometer,WEATHER,3.7,78
10836,Klart.se - Sweden's best weather,WEATHER,3.6,79
10837,SMHI Weather,WEATHER,3.5,80
10838,Storm Shield,WEATHER,3.5,81
10839,Sun & Moon AR Locator,WEATHER,3.3,82

Ranking restarts from 1 for every new category because of the PARTITION BY Category clause.
Unlike RANK(), ROW_NUMBER() assigns a unique rank to every app, even if multiple apps have the same rating.
This query helps identify the top-performing apps in each category rather than across the entire Play Store.
Businesses can compare the best apps within categories such as GAME, TOOLS, or FAMILY to understand what makes them successful.
It enables category-wise performance analysis, helping companies benchmark competitors and improve their own apps.

In [21]:
#Top Rated App in Each Category
query = """
SELECT *
FROM(
SELECT App,
Category,
Rating,
ROW_NUMBER() OVER(
PARTITION BY Category
ORDER BY Rating DESC
) rn
FROM apps
)
WHERE rn=1;
"""
pd.read_sql(query, conn)

,App,Category,Rating,rn
0,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1
1,Tickets SDA 2018 and Exam from the State Traff...,AUTO_AND_VEHICLES,4.9,1
2,"ipsy: Makeup, Beauty, and Tips",BEAUTY,4.9,1
3,R Programing Offline Tutorial,BOOKS_AND_REFERENCE,5.0,1
4,Ag Valley Cooperative,BUSINESS,5.0,1
5,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,1
6,BS-Mobile,COMMUNICATION,5.0,1
7,American Girls Mobile Numbers,DATING,5.0,1
8,"Learn Japanese, Korean, Chinese Offline & Free",EDUCATION,4.9,1
9,ðŸ”¥ Football Wallpapers 4K | Full HD Backgrou...,ENTERTAINMENT,4.7,1
10,SUMMER SONIC app,EVENTS,5.0,1
11,Hey AJ! It's Bedtime!,FAMILY,5.0,1
12,BI APP,FINANCE,5.0,1
13,Food-Aw - Order Food Online in Aruba,FOOD_AND_DRINK,5.0,1
14,Axe Champs! Wars,GAME,5.0,1
15,BM Physiotherapy Clinic,HEALTH_AND_FITNESS,5.0,1
16,"Viva Decora - Decoration, Photos, Architecture...",HOUSE_AND_HOME,4.8,1
17,Eternal life,LIBRARIES_AND_DEMO,5.0,1
18,Tafsiir Quraan MP3 Af Soomaali Quraanka Kariimka,LIFESTYLE,5.0,1
19,Tour BD (Bahir Dar Map),MAPS_AND_NAVIGATION,4.9,1
20,Super Hearing Secret Voices Recorder PRO,MEDICAL,5.0,1
21,AI Today : Artificial Intelligence News & AI 101,NEWS_AND_MAGAZINES,5.0,1
22,DF Glue Board,PARENTING,5.0,1
23,P-Home for KLWP,PERSONALIZATION,5.0,1
24,AJ Cam,PHOTOGRAPHY,5.0,1
25,BV Mobile Apps,PRODUCTIVITY,5.0,1
26,AJ RETAILS,SHOPPING,5.0,1
27,Eternal Light AG,SOCIAL,5.0,1
28,CricQuick,SPORTS,5.0,1
29,ADS-B Driver,TOOLS,5.0,1
30,BG Guide,TRAVEL_AND_LOCAL,5.0,1
31,AK Lodi Films,VIDEO_PLAYERS,4.9,1
32,Weather forecast,WEATHER,4.8,1

This query helps businesses identify the best-performing app in each category.
Companies can analyze these top-rated apps to understand the features, quality, and user experience that contribute to high ratings.
The results can be used for competitive analysis, market research, and benchmarking when developing new apps.

In [22]:
conn.close()